# Find all unused Ingress instances. 
# An Ingress instance is considered unused if:
# - default backend is not defined or not existings
# - none of referenced services (via spec.rules) exists
# 
# This does not take into account resource (field Resource *v1.TypedLocalObjectReference)
apiVersion: apps.projectsveltos.io/v1alpha1
kind: Cleaner
metadata:
  name: stale-ingresses
spec:
  schedule: "* 0 * * *"
  action: Delete # Delete matching resources
  resourcePolicySet:
    resourceSelectors:
    - kind: Ingress
      group: "networking.k8s.io"
      version: v1
    - kind: Service
      group: ""
      version: v1
    aggregatedSelection: |
      function getKey(namespace, name)
        return namespace .. ":" .. name
      end

      -- check default backend: if default backend is configured, return true
      -- if currently exists
      function isDefaultBackendValid(ingress, services)
        if ingress.spec.defaultBackend ~= nil then
          if ingress.spec.defaultBackend.service ~= nil then
            key = getKey(ingress.metadata.namespace, ingress.spec.defaultBackend.service.name)
            if services[key] then
              return true
            end
          end
        end
        return false
      end

      -- check if any referenced service (via rules) currently exists
      -- returns false only if none of the referenced services exists
      function isAnyReferencedServiceValid(ingress, services)
        if ingress.spec.rules ~= nil then
          for _,rule in ipairs(ingress.spec.rules) do
            if rule.http ~= nil and rule.http.paths ~= nil then
              for _,path in ipairs(rule.http.paths) do
                if path.backend.service ~= nil then
                  key = getKey(ingress.metadata.namespace, path.backend.service.name)
                  if services[key] then
                    return true
                  end
                end
              end
            end
          end
        end 
        return false
      end


      function evaluate()
        local hs = {}
        hs.valid = true
        hs.message = ""
        
        local services = {}
        local ingresses = {}
        local unusedIngresses = {}

        -- Separate ingresses and services from the resources
        -- Store existing services in a map like struct
        for _, resource in ipairs(resources) do
          local kind = resource.kind
          if kind == "Ingress" then
            table.insert(ingresses, resource)
          elseif kind == "Service" then
            key = getKey(resource.metadata.namespace,resource.metadata.name)
            print(key)
            services[key] = true
          end
        end

        for _,ingress in ipairs(ingresses) do
          local used = false
          key = getKey(ingress.metadata.namespace, ingress.metadata.name)
          if isDefaultBackendValid(ingress, services) then
            used = true
          elseif isAnyReferencedServiceValid(ingress, services) then
            used = true
          end

          if not used then
            table.insert(unusedIngresses, {resource = ingress})
          end
        end

        if #unusedIngresses > 0 then
          hs.resources = unusedIngresses
        end
        return hs
      end