---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cleany.wys1203.com
  resources:
  - cleaners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cleany.wys1203.com
  resources:
  - cleaners/finalizers
  verbs:
  - update
- apiGroups:
  - cleany.wys1203.com
  resources:
  - cleaners/status
  verbs:
  - get
  - patch
  - update
