# This Cleaner instance will find StatefulSet instances in all namespaces
# with has no associated Autoscaler and instructs Cleaner to
# delete those instances
apiVersion: apps.projectsveltos.io/v1alpha1
kind: Cleaner
metadata:
  name: statefulset-with-no-autoscaler
spec:
  schedule: "* 0 * * *"
  action: Delete # Delete matching resources
  resourcePolicySet:
    resourceSelectors:
    - kind: StatefulSet
      group: "apps"
      version: v1
    - kind: HorizontalPodAutoscaler
      group: "autoscaling"
      version: v2
    aggregatedSelection: |
      function evaluate()
        local hs = {}
        hs.message = ""

        local statefulSets = {}
        local autoscalers = {}
        local statefulSetWithNoAutoscaler = {}

        -- Separate statefulSets and services from the resources
        for _, resource in ipairs(resources) do
          local kind = resource.kind
          if kind == "StatefulSet" then
            table.insert(statefulSets, resource)
          elseif kind == "HorizontalPodAutoscaler" then
            if resource.spec.scaleTargetRef.kind == "StatefulSet" then
              table.insert(autoscalers, resource)
            end
          end
        end

        -- Check for each statefulSets if there is a matching HorizontalPodAutoscaler
        for _, statefulSet in ipairs(statefulSets) do
            local statefulSetName = statefulSet.metadata.name
            local matchingAutoscaler = false

            for _, autoscaler in ipairs(autoscalers) do
              if autoscaler.metadata.namespace == statefulSet.metadata.namespace then
                if autoscaler.spec.scaleTargetRef.name == statefulSet.metadata.name then
                  matchingAutoscaler = true
                  break
                end
              end
            end

            if not matchingAutoscaler then
                table.insert(statefulSetWithNoAutoscaler, {resource = statefulSet})
                break
            end
        end

        if #statefulSetWithNoAutoscaler > 0 then
          hs.resources = statefulSetWithNoAutoscaler
        end
        return hs
      end